### ISSUE TITLE
Research DCT

### ISSUE THREAD

**Issue by tchojnacki** [PWR-ACS-SE-24/EoSaKAfDaD#14]

**Comment by mlodybercik** [comment]
Glad I got assigned!

[JPEG Header Viewer](https://cyber.meme.tips/jpdump/#)
[W3 documentation about JPEG (?)](https://www.w3.org/Graphics/JPEG/itu-t81.pdf)

How I see the next stage:
1. Read JPEG the way we do it in stage 1 (put raw pixel data into canvas),
2. Re-encode new JPEG into memory (we need some particular jpeg encoder settings for it to be easier, mainly: not progressive and using `Baseline DCT`),
3. Read JPEG, find `SOS` - (`Start of scan` header) and edit it acording to our needs,
4. Present edited file to the user.
