### ISSUE TITLE
Rewrite `image-upload` to use animations

### ISSUE THREAD

**Issue by mlodybercik** [PWR-ACS-SE-24/EoSaKAfDaD#33]

**Comment by mlodybercik** [comment]
Using shared animations works (by creating template), but in case of `image-upload` it somehow collides with synchronous work being done by the browser. In Firefox 133.0 just after submitting new file, it flashes twice (animation starts, green is turning white, but after 100ms-150ms it restarts to the beginning and then plays like normal). In Chrome 123.0 it does **not** happen at all. Old animation method works flawlessly.

I'll push what I've done. I'll do more investigating in the morning. 

@tchojnacki wanna look at this?

**Comment by tchojnacki** [comment]
```TS
  private flash(type: Flash): void {
    this.flashState.set(type);
  }
```
|
v
```TS
  private flash(type: Flash): void {
    requestAnimationFrame(() => this.flashState.set(type));
  }
```

Would this help in any way?

**Comment by mlodybercik** [comment]
> Would this help in any way?

It does not.

It's a firefox bug. It's related to background tasks while animating. Bugzilla issues are open and left on `wontfix` or very low severity. But why does animating the old way not cause the same issue? It has to be linked in some way to Angular doing its animations.

https://bugzilla.mozilla.org/show_bug.cgi?id=1760795
https://bugzilla.mozilla.org/show_bug.cgi?id=1839022
https://bugzilla.mozilla.org/show_bug.cgi?id=1926870
